import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Toaster
        position="top-center"
        toastOptions={{
          style: {
            fontSize: "14px",
            padding: "14px",
            maxWidth: "500px",
            alignItems: "center",
            justifyContent: "center",
          },
        }}
      />
    </html>
  );
}
